baseURL = "/"
languageCode = "en-us"
title = "json api"

[outputs]
  page = ["json","authors"]
  home = ["json"]
  domains = ["json"]
  section = ["json"]
  taxonomy = ["json", "authors"]

[outputFormats.authors]
  baseName = "authors"
  mediatype ="application/json"

[taxonomies]
  sport = "sports"
  practice = "practices"

[permalinks]
  page = "/:section/:title/"